
exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('ingredients').del()
    .then(function () {
      // Inserts seed entries
      return knex('ingredients').insert([
        // biscuits and gravy
        { ingredient_id: 1, ingredient_name: 'milk' },
        { ingredient_id: 2, ingredient_name: 'salt' },
        { ingredient_id: 3, ingredient_name: 'black pepper' },
        { ingredient_id: 4, ingredient_name: 'garlic powder' },
        { ingredient_id: 5, ingredient_name: 'onion powder' },
        { ingredient_id: 6, ingredient_name: 'white pepper' },
        { ingredient_id: 7, ingredient_name: 'rendered clarified bacon fat' },
        // spaghetti
        { ingredient_id: 8, ingredient_name: 'water' },
        { ingredient_id: 9, ingredient_name: 'spaghetti noodles' },
        { ingredient_id: 10, ingredient_name: 'spaghetti sauce' },
        { ingredient_id: 11, ingredient_name: 'garlic cloves' },
        { ingredient_id: 12, ingredient_name: 'oregano' },
        { ingredient_id: 13, ingredient_name: 'basil' },
        { ingredient_id: 14, ingredient_name: 'italian sausage' },
        { ingredient_id: 15, ingredient_name: 'parmesan cheese' },
        { ingredient_id: 16, ingredient_name: 'mozzarella cheese' },
        { ingredient_id: 17, ingredient_name: 'bay leaves' },
        // french toast
        { ingredient_id: 18, ingredient_name: 'butter' },
        { ingredient_id: 19, ingredient_name: 'sugar' },
        { ingredient_id: 20, ingredient_name: 'vanilla extract' },
        { ingredient_id: 21, ingredient_name: 'large eggs' },
        { ingredient_id: 22, ingredient_name: 'baking powder' },
        { ingredient_id: 23, ingredient_name: 'baking soda' },
        { ingredient_id: 24, ingredient_name: 'potato bread' },
        { ingredient_id: 25, ingredient_name: 'rum extract' },
        { ingredient_id: 26, ingredient_name: 'nutmeg' },
        { ingredient_id: 27, ingredient_name: 'cinnamon' },
        { ingredient_id: 28, ingredient_name: 'allspice' },
        { ingredient_id: 29, ingredient_name: 'cooked and drained breakfast sausage crumbles' },
        { ingredient_id: 30, ingredient_name: 'cooked and drained italian sausage crumbles' },
      ]);
    })
    .then(() => {
      return knex('recipes').del()
        .then(function () {
          return knex('recipes').insert([
            { recipe_id: 1, recipe_name: 'biscuits and gravy', recipe_created_at: '2018-11-13T00:15:22.000Z' },
            { recipe_id: 2, recipe_name: 'spaghetti', recipe_created_at: '2018-11-13T00:15:22.000Z' },
            { recipe_id: 3, recipe_name: 'french toast', recipe_created_at: '2018-11-13T00:15:22.000Z' },
          ]);
        })
    })
    .then(() => {
      return knex('steps').del()
        .then(function () {
          return knex('steps').insert([
            {
              step_id: 1,
              recipe_id: 1,
              step_number: 1,
              step_instructions: 'Heat ingredients in a cast iron skillet over medium heat',
              quantity: "3 tablespoons",
              ingredient_id: 7,
            },
            {
              step_id: 2,
              recipe_id: 1,
              step_number: 2,
              step_instructions: 'Add to skillet',
              quantity: "1/2 teaspoon",
              ingredient_id: 2,
            },
            {
              step_id: 3,
              recipe_id: 1,
              step_number: 3,
              step_instructions: 'Add to skillet',
              quantity: "1/4 teaspoon",
              ingredient_id: 3,
            },
            {
              step_id: 4,
              recipe_id: 1,
              step_number: 4,
              step_instructions: 'Add to skillet',
              quantity: "1/4 teaspoon",
              ingredient_id: 4,
            },
            {
              step_id: 5,
              recipe_id: 1,
              step_number: 5,
              step_instructions: 'Add to skillet',
              quantity: "1/4 teaspoon",
              ingredient_id: 5,
            },
            {
              step_id: 6,
              recipe_id: 1,
              step_number: 6,
              step_instructions: 'Add to skillet',
              quantity: "1/4 teaspoon",
              ingredient_id: 6,
            },
            {
              step_id: 7,
              recipe_id: 1,
              step_number: 7,
              step_instructions: 'Add slowly to skillet, stirring',
              quantity: "2 cups",
              ingredient_id: 1,
            },
            {
              step_id: 8,
              recipe_id: 1,
              step_number: 8,
              step_instructions: 'Continue to cook until the mixture is thick and the gravy is bubbling',
              quantity: null,
              ingredient_id: null,
            },
            {
              step_id: 9,
              recipe_id: 1,
              step_number: 9,
              step_instructions: 'Add to skillet',
              quantity: "1/2 pound",
              ingredient_id: 29,
            },
            // spaghetti
            {
              step_id: 10,
              recipe_id: 2,
              step_number: 1,
              step_instructions: 'Heat water to boiling in a large pot',
              quantity: "6 cups",
              ingredient_id: 8,
            },
            {
              step_id: 11,
              recipe_id: 2,
              step_number: 2,
              step_instructions: 'Add pasta to boiling water',
              quantity: "8 ounces",
              ingredient_id: 8,
            },
            {
              step_id: 12,
              recipe_id: 2,
              step_number: 3,
              step_instructions: 'Boil for 10 minutes, drain, and rinse with cold water',
              quantity: "",
              ingredient_id: 2,
            },
            {
              step_id: 13,
              recipe_id: 2,
              step_number: 4,
              step_instructions: 'Heat spaghetti sauce in a large saucepan over medium heat',
              quantity: "1 jar",
              ingredient_id: 10,
            },
            {
              step_id: 14,
              recipe_id: 2,
              step_number: 5,
              step_instructions: 'Add sausage to sauce',
              quantity: "1/2 pound",
              ingredient_id: 14,
            },
            {
              step_id: 15,
              recipe_id: 2,
              step_number: 6,
              step_instructions: 'Simmer for 5 minutes',
              quantity: null,
              ingredient_id: null,
            },
            {
              step_id: 16,
              recipe_id: 2,
              step_number: 7,
              step_instructions: 'Add cheese to sauce',
              quantity: "1 cup",
              ingredient_id: 16,
            },
            {
              step_id: 17,
              recipe_id: 2,
              step_number: 8,
              step_instructions: 'Serve pasta over noodles and garnish',
              quantity: null,
              ingredient_id: 15,
            },
            // french toast
            {
              step_id: 18,
              recipe_id: 3,
              step_number: 1,
              step_instructions: 'Heat cast iron griddle over medium heat',
              quantity: null,
              ingredient_id: null,
            },
            {
              step_id: 19,
              recipe_id: 3,
              step_number: 2,
              step_instructions: 'Meanwhile, melt butter in a small saucepan over low heat',
              quantity: "1 stick",
              ingredient_id: 18,
            },
            {
              step_id: 20,
              recipe_id: 3,
              step_number: 3,
              step_instructions: 'Add to mixing bowl',
              quantity: "3",
              ingredient_id: 21,
            },
            {
              step_id: 21,
              recipe_id: 3,
              step_number: 4,
              step_instructions: 'Add to mixing bowl',
              quantity: "1/2 cup",
              ingredient_id: 19,
            },
            {
              step_id: 22,
              recipe_id: 3,
              step_number: 5,
              step_instructions: 'Add to mixing bowl',
              quantity: "1 teaspoon",
              ingredient_id: 20,
            },
            {
              step_id: 23,
              recipe_id: 3,
              step_number: 6,
              step_instructions: 'Add to mixing bowl',
              quantity: "1 teaspoon",
              ingredient_id: 22,
            },
            {
              step_id: 24,
              recipe_id: 3,
              step_number: 7,
              step_instructions: 'Add to mixing bowl',
              quantity: "1/4 teaspoon",
              ingredient_id: 23,
            },
            {
              step_id: 25,
              recipe_id: 3,
              step_number: 8,
              step_instructions: 'Add to mixing bowl',
              quantity: "1 tablespoon",
              ingredient_id: 25,
            },
            {
              step_id: 26,
              recipe_id: 3,
              step_number: 9,
              step_instructions: 'Add to mixing bowl',
              quantity: "1 teaspoon",
              ingredient_id: 26,
            },
            {
              step_id: 27,
              recipe_id: 3,
              step_number: 10,
              step_instructions: 'Add to mixing bowl',
              quantity: "1 teaspoon",
              ingredient_id: 27,
            },
            {
              step_id: 28,
              recipe_id: 3,
              step_number: 11,
              step_instructions: 'Add to mixing bowl',
              quantity: "1/2 teaspoon",
              ingredient_id: 28,
            },
            {
              step_id: 29,
              recipe_id: 3,
              step_number: 12,
              step_instructions: 'Mix well',
              quantity: null,
              ingredient_id: null,
            },
            {
              step_id: 30,
              recipe_id: 3,
              step_number: 13,
              step_instructions: 'soak bread slices in mixture until saturated',
              quantity: "4",
              ingredient_id: 24,
            },
            {
              step_id: 31,
              recipe_id: 3,
              step_number: 14,
              step_instructions: 'Place slices on the hot griddle and cook until golden brown',
              quantity: "4",
              ingredient_id: null,
            },
          ]);
        })
    })
};
